#!/bin/sh
# Regenerate locales/fieldlock.pot from the source, merge it into every
# existing .po, and compile the .mo files GLPI actually loads.
#
# Run from anywhere; requires the GNU gettext tools (xgettext, msggrep,
# msgmerge, msgfmt).
set -eu

cd "$(dirname "$0")/.."
LOCALES=locales
DOMAIN=fieldlock

# Strings called as __('Assets') with no domain resolve against GLPI's own
# catalog, so they must not end up in the plugin's. Keep this in sync with the
# group labels in PluginFieldlockLock::getItemtypeGroups().
CORE_STRINGS='^(Assistance|Assets|Management|Tools|Administration)$'

echo "==> extracting strings"
xgettext \
    --from-code=UTF-8 --language=PHP --no-wrap \
    --keyword=__:1 --keyword=_n:1,2 --keyword=_x:1c,2 --keyword=_nx:1c,2,3 \
    --package-name="Field Lock" \
    --package-version="$(sed -n "s/.*PLUGIN_FIELDLOCK_VERSION', '\([^']*\)'.*/\1/p" setup.php)" \
    --copyright-holder="Ampris" --msgid-bugs-address="" \
    --add-comments=TRANS --sort-by-file \
    -o "$LOCALES/$DOMAIN.pot.tmp" \
    $(find . -name '*.php' -not -path './locales/*' | sort)

echo "==> dropping strings owned by GLPI core"
msggrep --invert-match --msgid -E -e "$CORE_STRINGS" \
    -o "$LOCALES/$DOMAIN.pot" "$LOCALES/$DOMAIN.pot.tmp"
rm -f "$LOCALES/$DOMAIN.pot.tmp"

# Replace xgettext's placeholder preamble with something meaningful.
sed -i \
    -e '1s/.*/# Field Lock - GLPI plugin: translation template./' \
    -e "2s/.*/# Copyright (C) $(date +%Y) Ampris/" \
    -e '4s/.*/# Generated by tools\/update-locales.sh - do not translate this file directly./' \
    "$LOCALES/$DOMAIN.pot"

for po in "$LOCALES"/*.po; do
    [ -e "$po" ] || continue
    lang=$(basename "$po" .po)
    echo "==> $lang"
    msgmerge --quiet --no-wrap --update --backup=none "$po" "$LOCALES/$DOMAIN.pot"
    # GLPI loads locales/<lang>.mo (see Plugin::loadLang).
    msgfmt --check --statistics -o "$LOCALES/$lang.mo" "$po"
done

echo "==> done"
